# Generated by Django 3.1.4 on 2021-02-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='mode',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
